repos:
  - repo: local
    hooks:
      - id: mojo-format
        name: mojo-format
        entry: pixi run mojo format
        language: system
        files: '\.(mojo|🔥)$'
        stages: [pre-commit]

      - id: ruff-format
        name: ruff-format
        entry: pixi run ruff format
        language: system
        files: '\.py$'
        stages: [pre-commit]

      - id: debug-assert-messages
        name: debug-assert-messages
        entry: python3 scripts/check_debug_assert_messages.py
        language: system
        files: '\.(mojo|🔥)$'
        stages: [pre-commit]

      - id: organize-mojo-imports
        name: organize-mojo-imports
        entry: python3 scripts/organize_mojo_imports.py --check
        language: system
        files: '\.(mojo|🔥)$'
        stages: [pre-commit]
