"""Type stubs for the _decimo Mojo extension module.

This file tells Pylance/mypy the interface of the compiled _decimo.so.
"""

from typing import Any

class Decimal:
    def __init__(self, value: str | int | float) -> None: ...
    # Plain names, kept alongside the operators.
    def to_string(self) -> str: ...
    def to_repr(self) -> str: ...
    def add(self, other: Any) -> Decimal: ...
    def sub(self, other: Any) -> Decimal: ...
    def mul(self, other: Any) -> Decimal: ...
    def div(self, other: Any) -> Decimal: ...
    def neg(self) -> Decimal: ...
    def abs_(self) -> Decimal: ...
    def eq(self, other: Any) -> bool: ...
    def lt(self, other: Any) -> bool: ...
    def le(self, other: Any) -> bool: ...
    # Operators.
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __add__(self, other: Any) -> Decimal: ...
    def __radd__(self, other: Any) -> Decimal: ...
    def __sub__(self, other: Any) -> Decimal: ...
    def __rsub__(self, other: Any) -> Decimal: ...
    def __mul__(self, other: Any) -> Decimal: ...
    def __rmul__(self, other: Any) -> Decimal: ...
    def __truediv__(self, other: Any) -> Decimal: ...
    def __rtruediv__(self, other: Any) -> Decimal: ...
    def __neg__(self) -> Decimal: ...
    def __pos__(self) -> Decimal: ...
    def __abs__(self) -> Decimal: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
