"""Type stubs for the _decimo Mojo extension module.

This describes what the compiled `_decimo.so` provides. The names that
`decimo/__init__.py` adds afterwards -- `__hash__`, `as_tuple`,
`as_integer_ratio`, `__format__`, `from_float` and the context functions --
are declared there, not here.
"""

from typing import Any

def get_precision() -> int: ...
def set_precision(value: int) -> None: ...
def get_rounding() -> str: ...
def set_rounding(value: str) -> None: ...

class Decimal:
    def __init__(self, value: str | int | float | Decimal = ...) -> None: ...

    # Text.
    def to_string(self) -> str: ...
    def to_repr(self) -> str: ...
    def to_eng_string(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    # Arithmetic. Rounds to the context precision, as `decimal` does.
    def __add__(self, other: Any) -> Decimal: ...
    def __radd__(self, other: Any) -> Decimal: ...
    def __sub__(self, other: Any) -> Decimal: ...
    def __rsub__(self, other: Any) -> Decimal: ...
    def __mul__(self, other: Any) -> Decimal: ...
    def __rmul__(self, other: Any) -> Decimal: ...
    def __truediv__(self, other: Any) -> Decimal: ...
    def __rtruediv__(self, other: Any) -> Decimal: ...
    def __floordiv__(self, other: Any) -> Decimal: ...
    def __rfloordiv__(self, other: Any) -> Decimal: ...
    def __mod__(self, other: Any) -> Decimal: ...
    def __rmod__(self, other: Any) -> Decimal: ...
    def __divmod__(self, other: Any) -> tuple[Decimal, Decimal]: ...
    def __rdivmod__(self, other: Any) -> tuple[Decimal, Decimal]: ...
    def __pow__(self, other: Any) -> Decimal: ...
    def __rpow__(self, other: Any) -> Decimal: ...
    def __neg__(self) -> Decimal: ...
    def __pos__(self) -> Decimal: ...
    def __abs__(self) -> Decimal: ...
    def __bool__(self) -> bool: ...

    # Conversion.
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __trunc__(self) -> int: ...
    def __floor__(self) -> int: ...
    def __ceil__(self) -> int: ...
    def __round__(self, ndigits: int | None = ...) -> Any: ...
    def _components(self) -> tuple[bool, str, int]: ...

    # Comparison.
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def compare(self, other: Any) -> Decimal: ...
    def max(self, other: Any) -> Decimal: ...
    def min(self, other: Any) -> Decimal: ...

    # The rest of the `decimal.Decimal` surface.
    def quantize(self, exp: Any, rounding: str | None = ...) -> Decimal: ...
    def sqrt(self, context: Any = ...) -> Decimal: ...
    def exp(self, context: Any = ...) -> Decimal: ...
    def ln(self, context: Any = ...) -> Decimal: ...
    def log10(self, context: Any = ...) -> Decimal: ...
    def to_integral_value(self, rounding: str | None = ...) -> Decimal: ...
    def to_integral(self, rounding: str | None = ...) -> Decimal: ...
    def fma(self, other: Any, third: Any) -> Decimal: ...
    def normalize(self) -> Decimal: ...
    def adjusted(self) -> int: ...
    def scaleb(self, other: Any) -> Decimal: ...
    def copy_abs(self) -> Decimal: ...
    def copy_negate(self) -> Decimal: ...
    def copy_sign(self, other: Any) -> Decimal: ...
    def same_quantum(self, other: Any) -> bool: ...
    def is_zero(self) -> bool: ...
    def is_signed(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def is_nan(self) -> bool: ...
    def is_infinite(self) -> bool: ...
    def is_canonical(self) -> bool: ...
    def canonical(self) -> Decimal: ...
    def conjugate(self) -> Decimal: ...
    def radix(self) -> Decimal: ...
    def copy(self) -> Decimal: ...
